export { default as AdminLayout } from './AdminLayout.vue'
export { default as OverviewTab } from './OverviewTab.vue'
export { default as UserManagement } from './UserManagement.vue'
export { default as ProblemManagement } from './ProblemManagement.vue'
export { default as ProblemEdit } from './ProblemEdit.vue'
export { default as TagManagement } from './TagManagement.vue'
